/**:
  ros__parameters:

    motor:
      count:   2
      rids:    ["M1",      "M2"]
      hids:    [1,         2]
      ports:   ["CAN1",    "CAN1"]
      brands:  ["DJI",     "DJI"]
      types:   ["3508",    "3508"]

      p2v:
        kps:   [2.8E+1,    2.8E+1]
        kis:   [0.0E+0,    0.0E+0]
        kds:   [1.0E+3,    1.0E+3]

      v2c:
        kps:   [7.0E-3,    7.0E-3]
        kis:   [1.5E-2,    1.5E-2]
        kds:   [0.0E+3,    0.0E+3]